version: '3'
services:
  stable-diffusion:
    build:
      context: .
      dockerfile: Dockerfile.Stable
    ports:
      - 7860:7860
    environment:
      - CLI_ARGS=--api --api-log
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
